# Generated by Django 5.1.6 on 2025-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('picture', models.BinaryField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer_customer_demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'customer_customer_demo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer_demographics',
            fields=[
                ('customer_type_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('customer_desc', models.TextField()),
            ],
            options={
                'db_table': 'customer_demographics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250)),
                ('contact_name', models.CharField(max_length=250)),
                ('contact_title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('fax', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_territories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('title_of_courtesy', models.CharField(max_length=250)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('home_phone', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=250)),
                ('photo', models.BinaryField()),
                ('notes', models.TextField()),
                ('photo_path', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('freight', models.FloatField()),
                ('ship_name', models.CharField(max_length=250)),
                ('ship_address', models.CharField(max_length=250)),
                ('ship_city', models.CharField(max_length=250)),
                ('ship_region', models.CharField(max_length=250)),
                ('ship_postal_code', models.CharField(max_length=250)),
                ('ship_country', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('quantity_per_unit', models.CharField(max_length=250)),
                ('unit_price', models.FloatField()),
                ('units_in_stock', models.PositiveSmallIntegerField()),
                ('units_on_order', models.PositiveSmallIntegerField()),
                ('reorder_level', models.PositiveSmallIntegerField()),
                ('discontinued', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipper_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250)),
                ('contact_name', models.CharField(max_length=250)),
                ('contact_title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('fax', models.CharField(max_length=250)),
                ('homepage', models.TextField()),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('territory_description', models.CharField()),
            ],
            options={
                'db_table': 'territories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Us_states',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=250)),
                ('state_abbr', models.CharField(max_length=250)),
                ('state_region', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'us_states',
                'managed': False,
            },
        ),
    ]
