# Generated by Django 5.1.6 on 2025-03-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productlist_productlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.products'),
        ),
        migrations.AlterField(
            model_name='productlistentry',
            name='product_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='main.productlist'),
        ),
    ]
