# Generated by Django 5.1.6 on 2025-03-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productlistentry_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='main.products'),
        ),
    ]
